### ISSUE TITLE
Getting Server Error (500)

### ISSUE THREAD

**Issue by omarmeky** [gr2m/CORS-Proxy#23]
I've been successfully using corsproxy and then all of a sudden (about 1-2 months ago) I started getting this error:

An error has occurred: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}

I still can't figure out what is causing it. I've tried starting the proxy on various ports with no success.

**Comment by gr2m** [comment]
Hey, I've redone `corsproxy` and published 1.0.0. Let me know if you still run into issue
