### ISSUE TITLE
Unsure of How Exactly to Use Corsproxy

### ISSUE THREAD

**Issue by phlie** [gr2m/CORS-Proxy#27]
Hi there,

I managed to get corsproxy to work to load wikipedia inside of an object but don't understand how I can use it to load another site like Google. I've looked everywhere I can and cannot seem to come up with a solution. I would preferably like to load Google inside of an object but any other way to load it would be good to.

Thanks

**Comment by gr2m** [comment]
Hey @phlie, loading all pages should work the same. Can you clarify what exact problem you run into? If it's not an issue for you anymore, feel free to just close the issue :)
