### ISSUE TITLE
Throws exception when following example instructions

### ISSUE THREAD

**Issue by perqa** [gr2m/CORS-Proxy#29]
Excellent tool, but I have some issues with usage:

Starting from command prompt:
```
corsproxy
-bash: corsproxy: command not found
```

Created example file cors-proxy.js:
```
var cors_proxy = require("corsproxy");
var http_proxy = require("http-proxy");
http_proxy.createServer(cors_proxy).listen(1234);
```
Starting example file with:
```
node cors-proxy.js 
```
Opening URL *http://localhost:1234/www.google.com* results in:
```
node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
          ^
Error: Must provide a proper URL as target
    at ProxyServer.<anonymous> (/Users/perqa/Workspace/project/node_modules/http-proxy/lib/http-proxy/index.js:68:35)
    at Server.closure (/Users/perqa/Workspace/project/node_modules/http-proxy/lib/http-proxy/index.js:125:43)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2113:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at Socket.socket.ondata (http.js:1971:22)
    at TCP.onread (net.js:528:27)
```

The only way I got it working as expected was:
```
node node_modules/corsproxy/bin/index.js 
CORS Proxy started on 127.0.0.1:9292
```

What is wrong here, do you think?

**Comment by gr2m** [comment]
yeah the instructions might not be entirely clear, I (or someone else :) ) need to clean up the README and the code itself.

Main confusion is, you cannot directly open `http://localhost:1234/www.google.com`. You have to load it from another page, so that a referrer header gets sent. The referrer is needed to dynamically set the `allowed-host` cors header, that's why you see the error.

**Comment by perqa** [comment]
What I want to do is to route certain Angular $http requests from my app via the proxy, but that doesn't seem work either. I get the same error. How should it be done?

**Comment by Ehesp** [comment]
Also having the same issue, and also trying to do the same as @perqa

**Comment by maciejjankowski** [comment]
I tried using it for ajax call from my app found on `localhost:8082` with jQuery.

ajax url is then `http://localhost:1234/targetwebsite.pl/webapi/json` - right?

it crashes with the same error. I don't understand :/

**Comment by gr2m** [comment]
Okay, give me some time, I'll redo the whole Proxy Code, it's really old and I got much better at this mean while :) I'll try to look into it next week

**Comment by gr2m** [comment]
Hey, I've updated the CORS proxy, it's all new, based on hapi now. Could you give it a try now?
