### ISSUE TITLE
Corsproxy throws

### ISSUE THREAD

**Issue by neojski** [gr2m/CORS-Proxy#30]
I just ran corsproxy and navigated to http://localhost:1337/daleharvey.iriscouch.com/grocery/1323263686230-12546e1c-0087-4774-91fc-1407f2ad9306. Corsproxy throws the following.

```
150504/162029.577, [log,info], data: CORS Proxy running at:http://arch:1337
proxy to http://daleharvey.iriscouch.com/grocery/1323263686230-12546e1c-0087-4774-91fc-1407f2ad9306
Debug: internal, implementation, error 
    Error: "name" and "value" are required for setHeader().
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at Object.internals.transmit (/usr/lib/node_modules/corsproxy/node_modules/hapi/lib/transmit.js:251:25)
    at /usr/lib/node_modules/corsproxy/node_modules/hapi/lib/transmit.js:169:26
    at Function.internals.Auth.response (/usr/lib/node_modules/corsproxy/node_modules/hapi/lib/auth.js:381:16)
    at /usr/lib/node_modules/corsproxy/node_modules/hapi/lib/transmit.js:139:25
    at internals.Response._streamify (/usr/lib/node_modules/corsproxy/node_modules/hapi/lib/response.js:488:12)
    at internals.Response._marshal (/usr/lib/node_modules/corsproxy/node_modules/hapi/lib/response.js:434:21)
    at /usr/lib/node_modules/corsproxy/node_modules/hapi/lib/transmit.js:119:18
    at /usr/lib/node_modules/corsproxy/node_modules/hapi/lib/transmit.js:536:20
    at Object.exports.parallel (/usr/lib/node_modules/corsproxy/node_modules/hapi/node_modules/items/lib/index.js:47:9)
```

**Comment by gr2m** [comment]
I tried to debug it, but couldn't figure it out. I can reproduce it locally with daleharvey.iriscouch.com/grocery/1323263686230-12546e1c-0087-4774-91fc-1407f2ad9306, but not with other domains. Do you have access to the server logs of daleharvey.iriscouch.com? Can you tell if the server responses look good?

**Comment by gr2m** [comment]
It pretty much means that http://daleharvey.iriscouch.com/grocery/1323263686230-12546e1c-0087-4774-91fc-1407f2ad9306 returns `Client request error: connect ECONNREFUSED` for some reason, and cors proxy only takes that and adds the CORS headers to it

**Comment by gr2m** [comment]
I can reproduce the same error by just using https://www.npmjs.com/package/request:

```js
var url = 'http://daleharvey.iriscouch.com/grocery/1323263686230-12546e1c-0087-4774-91fc-1407f2ad9306'
require('request')(url, function(error) {
  console.log(error)
});
```

It's either a request issue, which is used within hapi, or more likely, something weird with iriscouch.com

**Comment by g-m-a** [comment]
Same issue. Any fix on this?

**Comment by gr2m** [comment]
@g-m-a are you also trying to connect to iriscouch.com?

**Comment by g-m-a** [comment]
@gr2m no, I am running a development server which uses an API from a live server. After some searching I found out this comes from node 0.12. For now, I just switched to node 0.10 and it is ok.

**Comment by gr2m** [comment]
@g-m-a thanks for letting me know, I'll look into it

**Comment by voltrevo** [comment]
Same issue here too :-(

**Comment by gr2m** [comment]
@voltrevo can you please describe the exact steps it takes to reproduce? If IrisCouch is involved, it's most likely an issue on their side, please try another URL then

**Comment by rainabba** [comment]
Don't have a clue how it would be related, but while working with hapi-auth-jwt2, I found this and at the surface, it looks like it might be related. https://github.com/dwyl/hapi-auth-jwt2/issues/84

**Comment by rainabba** [comment]
In short, if anything tries to call reply().header() with the value being undefined, this error will occur and without reference to the related plugin (if any). In my case, it was actually my doing, not a plugin and still not very clear.

**Comment by gr2m** [comment]
I've added a test to the server, and integrated it into a test suite that is now run on travis: https://travis-ci.org/gr2m/CORS-Proxy

You can start the test by setting `DEBUG=1`. Try the following

```
npm install -g corsproxy
DEBUG=1 corsproxy
```

Now open http://localhost:1338. You should see two examples with results at the bottom. The first one should say "Error", the second one should say "Success". If that's the case, then the proxy works as expected, and the issue lies most likely with the origin server, not with the proxy itself.

Please feel free to reopen this issue, or create a separate one, if you are still seeing problems. I'm sorry this took so long to look into
