### ISSUE TITLE
cors headers allowed as command-line option?

### ISSUE THREAD

**Issue by ip2k** [gr2m/CORS-Proxy#31]
It was trivial to modify https://github.com/gr2m/CORS-Proxy/blob/d1acc5522c247f5453bc1d6d837c46fb516f1c03/lib/add-cors-headers.js#L2 in my case to add `X-Transmission-Session-Id`, but maybe it'd be cool to allow a flag like `--additional-headers=['foo', 'bar']` when running this so anyone could specify extra headers they need. It doesn't look like it'd require much re-plumbing, but I've not worked tons with Node.

Here's the code in question:
`lib/add-cors-headers.js`
```
module.exports = function addCorsHeaders (request, reply) {
  var allowedHeaders = [
    'authorization',
    'content-length',
    'content-type',
    'if-match',
    'if-none-match',
    'origin',
    'x-requested-with'
  ]
```

**Comment by gr2m** [comment]
Actually, the list of allowedHeaders should be dynamically generated from the request. Wanna give that a try?

**Comment by gr2m** [comment]
it's set dynamically now.
