### ISSUE TITLE
Bad request on url which used to work

### ISSUE THREAD

**Issue by tbalouet** [gr2m/CORS-Proxy#32]
When I try to access the following url : 
http://localhost:9292/static.moviecrow.com/marquee/thaandavam-reviews-from-fdfs-viewers/8811_thumb_665.jpg
I get the following error message : 
`ERROR

The request could not be satisfied.

Bad request. 
Generated by cloudfront (CloudFront)
Request ID: PeNEDZYGuZR9ZUUDcSzGG9THp9LO2SfTCKUxDIxLv56_tPXs_8s-6A==`

The previous version of your code worked fine, but the node package version is 1.0.0 for both, so it's impossible to come back to old version. 

Great work though, but if it was possible to have a package for the older version, it would be great !

**Comment by gr2m** [comment]
you can install the old version with `npm install -g corsproxy@0.2.14`. The old versions are all on npm. 

Does this work now using the new Port number 1337?

**Comment by tbalouet** [comment]
Wonderful, the old version installs greatly, and it works. It's on port 9292 though.
Thanks for the quick answer !
