### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by blumonkey** [gr2m/CORS-Proxy#40]
I have installed corsproxy via npm and ran the corsproxy command to start the server but it doesn't look like its working. I get a ERR_CONNECTION_REFUSED on my browser. Any help? I also cant connect via `telnet`

**Comment by gr2m** [comment]
can you tell the exact steps you do, please?

**Comment by blumonkey** [comment]
`sudo npm install -g corsproxy`
`corsproxy`

Then I go to the browser or try some of the examples given, 
But I get a CONNREFUSED in the browser and in `telnet`

**Comment by gr2m** [comment]
You do not open a URL like http://localhost:1337/my.domain.com/path/to/resource directly, instead you call it from another domain. For example, open http://jquery.com/, open the console, and do `$.get('http://gregor.local:1337/example.com').done(alert.bind(window))`.

Does that work for you?

**Comment by blumonkey** [comment]
Nope. I get the following error:

    $.get('http://localhost:1337/example.com').done(alert.bind(window))
    =>jquery.min.js:4 GET http://localhost:1337/example.com net::ERR_CONNECTION_REFUSED

I really doubt that the service is running. How do I check that? There is no output in the console either when I start `corsproxy`.

**Comment by gr2m** [comment]
@blumonkey I've released a new version which includes a test server.

Can you try the following:

```
npm install -g corsproxy
DEBUG=1 corsproxy
```

Then open http://localhost:1338. You should see two examples with results below. The first one should say "Error", the second one should say "Success".

Does that work for you?
