### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by evertonberz** [gr2m/CORS-Proxy#41]
Hi

does CORS-Proxy have SSL support?

I mean I want to proxy to a HTTPS website.
Example:
curl -v http://corsproxyserver.xxx.com.br:1337/sslwebsite.xxx.com.br:443/

It could be a "no-check-certificate" access.

Thanks

**Comment by gr2m** [comment]
the proxy must be accessed via https:// in order to proxy an https:// page

**Comment by evertonberz** [comment]
I tried that but I got the error below:

```
# curl -insecure -v https://corsproxyserver.xxx.com.br:1337/sslwebsite.xxx.jus.br:443/jk?mime=prop
* Couldn't find host corsproxyserver.xxx.com.br in the _netrc file; using defaults
* Adding handle: conn: 0x2bf3c88
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x2bf3c88) send_pipe: 1, recv_pipe: 0
* About to connect() to corsproxyserver.xxx.com.br port 1337 (#0)
*   Trying 10.4.17.251...
* Connected to corsproxyserver.xxx.com.br (10.4.17.251) port 1337 (#0)
* successfully set certificate verify locations:
*   CAfile: C:\Program Files (x86)\cmder\vendor\msysgit\bin\curl-ca-bundle.crt
  CApath: none
* SSLv3, TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to corsproxyserver.xxx.com.br:1337
* Closing connection 0
```

Does corsproxy run over https too?
The message when I start corsproxy only shows http://

```
# corsproxy
150918/125612.364, [log,info], data: CORS Proxy running at: http://corsproxyserver.xxx.com.br:1337
```

**Comment by gr2m** [comment]
that's an issue with your SSL setup now though, not with CORS-Proxy.

**Comment by evertonberz** [comment]
No, it is not. CORS-Proxy did not even try to connect to my sslwebsite. 
I run a sniffer on the cors server and no packets were captured from cors to the website.

Could you please try to reproduce this test?

**Comment by evertonberz** [comment]
No, it's not.
The cors server did not even try to connect to my ssl website.
I run a sniffer in the cors server and no packets were captured.

```
[17:53:19] root@corsproxyserver.xxx.com.br:~ # tcpdump -s0 -n -XX host sslwebsite.xxx.com.br
...
# curl --insecure -v https://corsproxyserver.xxx.com.br:1337/sslwebsite.xxx.com.br:443/jk?mime=prop
```

Could you please try to reproduce this scenario?

**Comment by ldunca** [comment]
+1 does it support HTTPS?

**Comment by gr2m** [comment]
I'm quite sure it does, it always did, as long as the proxy was running on https itself. At least it worked on Heroku, but that might be their special setup.

I don't have enough knowledge of ssl to understand @evertonberz logs, I don't really get what the problem is. If you can track it down / fix it, please send a pull request

**Comment by yuryskaletskiy** [comment]
gr2m, it cannot be working properly because you are using "http" schema all times when connect to remote host. 

I'd propose the following maybe a little but dummy patch - force https if using 443 port in request uri

` mapUri: function (request, callback) {
        request.host = request.params.host
        var hostPort = request.host.split(":")
        var schema = "http"
        if (hostPort.length == 2 && hostPort[1] == 443)
                schema = "https"
        request.path = request.path.substr(request.params.host.length + 1)
        request.headers['host'] = request.host
        var query = request.url.search ? request.url.search : ''
        console.log('proxy to ' + schema + '://' + request.host + request.path)
        callback(null, schema + '://' + request.host + request.path + query, request.headers)
      }`

**Comment by MattiJarvinen-BA** [comment]
I would think adding protocol (http or https) straight into request itself like

`http://localhost:1337/https://domain.tld/path/to/resource` would make using cors proxy quite easy.

And just expect if protocol part is missing it's http

**Comment by gr2m** [comment]
that won’t work, https is an end-to-end encryption. You cannot connect to the CORS proxy with http and then forward to a domain with https. The protocol must be the same

**Comment by MattiJarvinen-BA** [comment]
My bad... was thinking that you actually make the request in the proxy and pass along the response instead of only proxying it.

**Comment by gerbil** [comment]
Any ideas for 'https' requests?

**Comment by fabio-looker** [comment]
This is a no brainer... Luckily someone did it!
https://github.com/larrysalibra/CORS-Proxy-https
