### ISSUE TITLE
Doesn't work correctly on OSX because hostname can't be specified

### ISSUE THREAD

**Issue by DaSchTour** [gr2m/CORS-Proxy#42]
On my mac the server doesn't run on localhost but with my Hostname.local
So it doesn't work together with my npm app that runs on localhost
It would be useful if the hostname could be added as a parameter!

**Comment by aj07mm** [comment]
not working here too

**Comment by gr2m** [comment]
I’m sorry but I’m not using `corsproxy` myself anymore. If you’d like to look into it and send a PR to resolve the issue, I’ll happily review it

**Comment by derwaldgeist** [comment]
@gr2m What are you using now instead? I just stumbled upon corsproxy, and it's really useful. Thanks for building it.

**Comment by gr2m** [comment]
@derwaldgeist I use [hapi](https://hapijs.com/) as my server framework and use [hapi-cors-headers](https://github.com/gr2m/hapi-cors-headers) to make routes support CORS

**Comment by derwaldgeist** [comment]
Wow, that was fast :-) Thanks for your reply!
