### ISSUE TITLE
Chinese garbage problem

### ISSUE THREAD

**Issue by jeneser** [gr2m/CORS-Proxy#46]
**I am a Chinese developer. In use, I met a Chinese distortion of the issue.** 
Use this proxy to access most of the site does not garbled. However, when I asked some of the url, the server returns a Chinese distortion, for use of other cross-border proxy test, and did not return garbled.
The url is: http: // localhost: 1337 / news.hpu.edu.cn / news / contents / 544 / 118139.html
I'm not sure this is what causes.
My operating system is ubuntu16.04, nodejs version is 4.2.6, the test browser is chromium

thanks！

**Comment by gr2m** [comment]
I'm sorry I can't help myself, I no longer use this project. But if you find the solution, I'm happy to accept a pull request
