### ISSUE TITLE
Use with webpack

### ISSUE THREAD

**Issue by kopax** [gr2m/CORS-Proxy#48]
When I am poroxying my reactjs application started using webpack, I encounter issue to proxy it correctly.

You can test it using the sample project here : https://github.com/mxstbr/react-boilerplate

This will throw errors when trying to access `http://localhost:1337/localhost:3000` from your browser : 

```
- 2016-10-19 02:27:52.315 localhost:3001:19 GET http://localhost:1337/reactBoilerplateDeps.dll.js 
- 2016-10-19 02:27:52.418 localhost:3001:19 GET http://localhost:1337/main.js 502 (Bad Gateway)
```

![image](https://cloud.githubusercontent.com/assets/1866564/19493475/f63746dc-95a4-11e6-8070-bf1283ed0b60.png)

Is there any way to fix this using CORS-Proxy ?

**Comment by gr2m** [comment]
I'm sorry I can't help myself, I no longer use this project. But if you find the solution, I'm happy to accept a pull request

**Comment by alvarom24** [comment]
I am having the same issue, once the page is loaded the console fire to much errors about bad gateway.
